language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
install:
  - travis_retry pip install coveralls tox==1.6.1
script:
  - travis_retry tox
after_success:
  - coveralls
